# Should be run from the workspace rot using
# docker build -f packages/{{ packageName }}/Dockerfile . 

FROM node:26.11.1-alpine AS build

WORKDIR /app

RUN apk add --no-cache python3 py3-pip build-base
RUN npm i -g corepack
RUN corepack enable

COPY scripts/ ./scripts/
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/{{ packageName }}/package.json ./packages/{{ packageName }}/package.json

RUN corepack install
RUN pnpm install --frozen-lockfile --filter={{ packageName }}

COPY packages/{{ packageName }}/ ./packages/{{ packageName }}/

RUN pnpm run validate

WORKDIR /app/packages/{{ packageName }}

RUN pnpm build
RUN pnpm assemble

FROM node:26.11.1-alpine AS runtime

ARG COMMIT_SHA=dev

ENV COMMIT_SHA=$COMMIT_SHA NODE_ENV=production

WORKDIR /app

COPY --from=build /app/packages/{{ packageName }}/.assembled/ ./

ENTRYPOINT ["node", "--enable-source-maps", "dist/index.mjs"]

HEALTHCHECK --interval=30s --timeout=5s --retries=2 --start-period=25s --start-interval=10s \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:4000/health || exit 1
